[server]
headless = true
fileWatcherType = "none"
runOnSave = false
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[runner]
fastReruns = false

[client]
showErrorDetails = true
